version: '3.8'

services:
  demo-env:
    build: .
    image: tools-demo-env:latest
    container_name: tools_demoenv
    ipc: host
    ports:
      - "3000:3000"
      - "8000:8000"
      - "9090:9090"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: terminator
