version: '3.8'

services:
  demo-env:
    build: .
    image: tools-demo-env:latest
    container_name: tools_demoenv
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: terminator
